Resolve syntax error in f-string with nested quotes
Previously, use of double quotes `"` inside the f-string for dict access caused a syntax error because the outer f-string's double quotes were prematurely terminated
To resolve, this commit switches to a single quote `'` within the f-string

```
mdolah@mdolah-MacBookPro:~/Documents/Work/terraform-scalr-migrate-tfc/tfc-runs »  . /Users/mdolah/.local/share/virtualenvs/tfc-runs-pAj-PGUU/bin/activate
(tfc-runs) mdolah@mdolah-MacBookPro:~/Documents/Work/terraform-scalr-migrate-tfc/tfc-runs(runs-mdolah⚡) » python3 runs.py list-all
  File "/Users/mdolah/Documents/Work/terraform-scalr-migrate-tfc/tfc-runs/runs.py", line 62
    "Authorization": f"Bearer {credentials_json["credentials"][hostname]["token"]}"
                                                 ^^^^^^^^^^^
SyntaxError: f-string: unmatched '['
```